plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '1.0.21'
    // later
    // id 'net.neoforged.moddev' version '2.0.105'
    id "me.modmuss50.mod-publish-plugin" version "2.2.0"
    id 'dev.mixinmcp.decompile' version '1.5.0'
}

tasks.named('wrapper', Wrapper).configure {
    // Define wrapper values here so as to not have to always do so when updating gradlew.properties.
    // Switching this to Wrapper.DistributionType.ALL will download the full gradle sources that comes with
    // documentation attached on cursor hover of gradle classes and methods. However, this comes with increased
    // file size for Gradle. If you do switch this to ALL, run the Gradle wrapper task twice afterwards.
    // (Verify by checking gradle/wrapper/gradle-wrapper.properties to see if distributionUrl now points to `-all`)
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id


repositories {
    mavenLocal()

    maven {
        url = uri("https://maven.shadowsoffire.dev/releases")
        content {
            includeGroup("dev.shadowsoffire")
            includeGroup("snownee.jade")
        }
    }
    maven {
        url = uri("https://cursemaven.com")
        content {
            includeGroup("curse.maven")
        }
    }
    maven {
        url = uri("https://api.modrinth.com/maven")
        content {
            includeGroup("maven.modrinth")
        }
    }

    maven {
        url "https://maven.theillusivec4.top/"
    }
    maven {
        url "https://maven.blamejared.com"
        content {
            includeGroup "vazkii.patchouli"
            includeGroupByRegex "net\\.darkhax.*"
            includeGroupByRegex "com\\.blamejared.*"
            includeGroup "org.openzen.zencode"
            includeGroup "mezz.jei"
        }
    }

    maven {
        name = "Curios"
        url = uri("https://maven.theillusivec4.top/")
    }
    maven { url 'https://maven.shedaniel.me/' }
    maven { url 'https://maven.kosmx.dev/' }

    maven { url "https://maven.wispforest.io/releases"}
    maven { url "https://maven.su5ed.dev/releases"}
    maven {
        name = "Iron's Maven - Release"
        url = "https://code.redspace.io/releases"
    }
    maven {
        name = "Iron's Maven - Snapshots"
        url = "https://code.redspace.io/snapshots"
    }
    repositories {
        maven {
            name = 'GeckoLib'
            url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
            content {
                includeGroup("software.bernie.geckolib")
            }
        }
    }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

java {
    withSourcesJar()
}

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            gameDirectory = project.file('run/client')
            programArguments.addAll('--quickPlayMultiplayer', 'localhost:25565')
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        clientExtra {
            client()
            gameDirectory = project.file('run/client2')
            programArguments.addAll('--username', 'Dev2', '--quickPlayMultiplayer', 'localhost:25565')
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            gameDirectory = project.file('run/server')
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        // applies to all the run configs above
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

// Sets up a dependency configuration called 'localRuntime'.
// This configuration should be used instead of 'runtimeOnly' to declare
// a dependency that will be present for runtime testing but that is
// "optional", meaning it will not be pulled by dependents of this mod.
configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    // Dev env
    localRuntime("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")
    localRuntime("snownee.jade:Jade-NeoForge:${minecraft_version}-${jade_version}")
    localRuntime("me.shedaniel.cloth:cloth-config-neoforge:${cloth_config}")

    // Apotheosis
    implementation("dev.shadowsoffire:Placebo:${minecraft_version}-${placebo}")
    implementation("dev.shadowsoffire:Apotheosis:${minecraft_version}-${apotheosis}")
    implementation("dev.shadowsoffire:ApothicAttributes:${minecraft_version}-${apothic_attributes}")
    localRuntime("dev.shadowsoffire:ApothicSpawners:${minecraft_version}-${apothic_spawners}")
    localRuntime("dev.shadowsoffire:ApothicEnchanting:${minecraft_version}-${apothic_enchanting}")
    // Override newer version of patchouli due to dev env crash
    localRuntime("vazkii.patchouli:Patchouli:${patchouli_version}")

    // Iron's Spells 'n Spellbooks
    implementation("io.redspace:irons_spellbooks:${irons_spellbooks}")
    localRuntime("io.redspace:irons_lib:${irons_lib}")
    localRuntime("software.bernie.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}")
    compileOnly("top.theillusivec4.curios:curios-neoforge:${curios_version}:api")
    localRuntime("top.theillusivec4.curios:curios-neoforge:${curios_version}")
    localRuntime("dev.kosmx.player-anim:player-animation-lib-forge:${player_animator}")

    // Optional compats

    // https://www.curseforge.com/minecraft/mc-mods/magic-from-the-east
    compileOnly("curse.maven:magic-from-the-east-1224162:7385201")
    localRuntime("curse.maven:magic-from-the-east-1224162:7385201")

    // https://www.curseforge.com/minecraft/mc-mods/snackpirates-aeromancy-additions
    // https://www.curseforge.com/minecraft/mc-mods/expandability
    compileOnly("curse.maven:snackpirates-aeromancy-additions-1160104:8251034")
    localRuntime("curse.maven:snackpirates-aeromancy-additions-1160104:8251034")
    localRuntime("curse.maven:expandability-465066:5428824")

    // https://www.curseforge.com/minecraft/mc-mods/cataclysm-spellbooks
    // https://www.curseforge.com/minecraft/mc-mods/aces-spell-utils
    // https://www.curseforge.com/minecraft/mc-mods/lendercataclysm
    // https://www.curseforge.com/minecraft/mc-mods/lionfish-api
    // https://www.curseforge.com/minecraft/mc-mods/azurelib
    compileOnly("curse.maven:cataclysm-spellbooks-1099461:8847070")
    localRuntime("curse.maven:cataclysm-spellbooks-1099461:8847070")
    compileOnly("curse.maven:aces-spell-utils-1299492:8789930")
    localRuntime("curse.maven:aces-spell-utils-1299492:8789930")
    localRuntime("curse.maven:lendercataclysm-551586:8706841")
    localRuntime("curse.maven:lionfish-api-1001614:8345326")
    localRuntime("curse.maven:azurelib-817423:8367232")

    // https://www.curseforge.com/minecraft/mc-mods/discerning-the-eldritch
    compileOnly("curse.maven:discerning-the-eldritch-1143065:8816497")
    localRuntime("curse.maven:discerning-the-eldritch-1143065:8816497")
    localRuntime("curse.maven:prometheus-1365195:7364871")
    localRuntime("curse.maven:soul-fire-d-662413:7364962")
    localRuntime("curse.maven:cobweb-968456:7186943")

    // https://www.curseforge.com/minecraft/mc-mods/monsters-spellbooks-iss
    compileOnly("curse.maven:monsters-spellbooks-iss-1428928:8788560")
    localRuntime("curse.maven:monsters-spellbooks-iss-1428928:8788560")

    // https://www.curseforge.com/minecraft/mc-mods/hazentouvelib
    // https://www.curseforge.com/minecraft/mc-mods/stars-align
    // https://www.curseforge.com/minecraft/mc-mods/eternal-starlight
    compileOnly("curse.maven:hazentouvelib-1528722:8666581")
    localRuntime("curse.maven:hazentouvelib-1528722:8666581")
    localRuntime("curse.maven:stars-align-1526398:8041593")
    localRuntime("curse.maven:eternal-starlight-1080592:8668881")
    localRuntime("com.illusivesoulworks.caelus:caelus-neoforge:${caelus_version}") // required by hazentouvelib

    // https://www.curseforge.com/minecraft/mc-mods/enders-spells-and-stuff-requiem
    compileOnly("curse.maven:enders-spells-and-stuff-requiem-1336977:8762149")
    localRuntime("curse.maven:enders-spells-and-stuff-requiem-1336977:8762149")

    // https://www.curseforge.com/minecraft/mc-mods/tunes-n-tomes-a-bards-journey
    compileOnly("curse.maven:tunes-n-tomes-a-bards-journey-1509193:8370271")
    localRuntime("curse.maven:tunes-n-tomes-a-bards-journey-1509193:8370271")

    // https://www.curseforge.com/minecraft/mc-mods/hazen-n-stuff
    compileOnly("curse.maven:hazen-n-stuff-1231627:8277644")
    localRuntime("curse.maven:hazen-n-stuff-1231627:8277644")

    // Compatibility testing only
    // https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks-restrictions
    // localRuntime("curse.maven:irons-spells-n-spellbooks-restrictions-1330168:8448221")

    // https://www.curseforge.com/minecraft/mc-mods/elemental-synergies
    // localRuntime("curse.maven:elemental-synergies-1364850:8901149")
}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishMods {
    file = jar.archiveFile
    modLoaders.add("neoforge")
    changelog = new File("$project.rootDir/CHANGELOG.md").getText('UTF-8')
    version = "${mod_version}+${minecraft_version}"
    type = STABLE
    displayName = "${mod_version}+${minecraft_version}"

    curseforge {
        projectId = "${curseforge_project}"
        accessToken = System.getenv("CF_TOKEN")

        minecraftVersions.add(minecraft_version)
        javaVersions.add(JavaVersion.VERSION_21)

        client = true
        server = true

        // Dependencies
        requires "apotheosis"
        requires "irons-spells-n-spellbooks"

        optional "cataclysm-spellbooks" // Abyssal
        optional "hazen-n-stuff" // Radiance, Shadow
        optional "tunes-n-tomes-a-bards-journey" // Melody (sound school)
        optional "snackpirates-aeromancy-additions" // Wind
        optional "magic-from-the-east" // Symmetry, Spirit
        optional "enders-spells-and-stuff-requiem" // Mind, Spellblade pending
    }

    //github {
   //     accessToken = providers.environmentVariable("GITHUB_TOKEN")
   //     repository = "muon-rw/Apotheosis-Irons-Spells"
    //    commitish = "master"
    //    tagName = "v${project.version}"
   // }
}

tasks.withType(GenerateModuleMetadata).configureEach {
    enabled = false
}

publishing {
    publications {
        create('mavenJava', MavenPublication) {
            groupId = 'dev.muon'
            artifactId = 'irons-apothic'
            version = "${mod_version}+${minecraft_version}"
            artifact(tasks.named('jar'))
            artifact(tasks.named('sourcesJar', Jar))
        }
    }
    repositories {
        maven {
            name = 'muonReleases'
            url = System.getenv('MAVEN_URL') ?: 'https://maven.muon.rip/releases/'
            credentials {
                username = System.getenv('MAVEN_USERNAME')
                password = System.getenv('MAVEN_PASSWORD')
            }
        }
    }
}

tasks.named('publishMods') {
    dependsOn 'publishAllPublicationsToMuonReleasesRepository'
}
tasks.withType(me.modmuss50.mpp.PublishModTask).configureEach {
    mustRunAfter 'publishAllPublicationsToMuonReleasesRepository'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
